[versions]
agp = "8.5.2"
androidSdk = "11.5.1"
androidx-activityCompose = "1.9.3"
androidx-lifecycle = "2.8.3"
appcompat = "1.6.1"
commonSdk = "0.0.3"
compose-multiplatform = "1.7.0"
constraintlayout = "2.2.0"
koin = "3.5.6"
kotlin = "2.0.21"
material = "1.9.0"
materialIconsExtended = "1.4.0"
mobileSdk = "1.0.3"
playServicesGcm = "17.0.0"
playServicesLocation = "21.3.0"
servicesSdk = "1.0.0"
material3Android = "1.3.1"
kotlinVersion = "1.9.0"

[libraries]
android-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "androidSdk" }
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout-v220 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
common-sdk = { module = "neshan-android-sdk:common-sdk", version.ref = "commonSdk" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
material-v190 = { module = "com.google.android.material:material", version.ref = "material" }
mobile-sdk = { module = "neshan-android-sdk:mobile-sdk", version.ref = "mobileSdk" }
play-services-gcm = { module = "com.google.android.gms:play-services-gcm", version.ref = "playServicesGcm" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
services-sdk = { module = "neshan-android-sdk:services-sdk", version.ref = "servicesSdk" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }